// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcuqzzabatzvvxikusja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdXF6emFiYXR6dnZ4aWt1c2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzU4OTAsImV4cCI6MjA2MzM1MTg5MH0.tCD8DsQqk7Azri1erdPZ94q90WtZryAFwF4urCT7IBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);